class TipuApiHelperMock
  def self.GetMunicipalities
    return  [{"id"=>"AHLAIN", "ely-centre"=>{"content"=>2, "name"=>"Varsinais-Suomen ELY"}, "centerpoint-lat"=>61.6666679, "old-county"=>{"content"=>2, "name"=>"TURKU - PORI, FINLAND"}, "joined-to"=>"", "centerpoint-lon"=>21.666666, "name"=>[{"content"=>"AHLAINEN", "lang"=>"FI"}, {"content"=>"AHLAINEN", "lang"=>"SV"}], "province"=>{"name"=>""}, "radius"=>20, "merikotka-suuralue"=>"S"},
             {"id"=>"AITOLA", "ely-centre"=>{"content"=>4, "name"=>"Pirkanmaan ELY"}, "centerpoint-lat"=>61.5499992, "old-county"=>{"content"=>4, "name"=>"HÄME, FINLAND"}, "joined-to"=>"", "centerpoint-lon"=>23.9166698, "name"=>[{"content"=>"AITOLAHTI", "lang"=>"FI"}, {"content"=>"AITOLAHTI", "lang"=>"SV"}], "province"=>{"name"=>""}, "radius"=>12, "merikotka-suuralue"=>"N"},
             {"id"=>"AKAA", "ely-centre"=>{"content"=>4, "name"=>"Pirkanmaan ELY"}, "centerpoint-lat"=>61.1500015, "old-county"=>{"content"=>4, "name"=>"HÄME, FINLAND"}, "joined-to"=>"AKAA", "centerpoint-lon"=>23.7333336, "name"=>[{"content"=>"AKAA", "lang"=>"FI"}, {"content"=>"AKAA", "lang"=>"SV"}], "province"=>{"content"=>6, "name"=>"Pirkanmaa"}, "radius"=>18, "merikotka-suuralue"=>"N"},
             {"id"=>"ALAHÄR", "ely-centre"=>{"content"=>10, "name"=>"Etelä-Pohjanmaan ELY"}, "centerpoint-lat"=>63.25, "old-county"=>{"content"=>9, "name"=>"VAASA, FINLAND"}, "joined-to"=>"", "centerpoint-lon"=>22.8333302, "name"=>[{"content"=>"ALAHÄRMÄ", "lang"=>"FI"}, {"content"=>"ALAHÄRMÄ", "lang"=>"SV"}], "province"=>{"name"=>""}, "radius"=>20, "merikotka-suuralue"=>"N"},
             {"id"=>"ALAJÄR", "ely-centre"=>{"content"=>10, "name"=>"Etelä-Pohjanmaan ELY"}, "centerpoint-lat"=>62.9500008, "old-county"=>{"content"=>9, "name"=>"VAASA, FINLAND"}, "joined-to"=>"ALAJÄR", "centerpoint-lon"=>24, "name"=>[{"content"=>"ALAJÄRVI", "lang"=>"FI"}, {"content"=>"ALAJÄRVI", "lang"=>"SV"}], "province"=>{"content"=>14, "name"=>"Etelä-Pohjanmaa"}, "radius"=>32, "merikotka-suuralue"=>"N"},
             {"id"=>"ALASTA", "ely-centre"=>{"content"=>2, "name"=>"Varsinais-Suomen ELY"}, "centerpoint-lat"=>60.966671, "old-county"=>{"content"=>2, "name"=>"TURKU - PORI, FINLAND"}, "joined-to"=>"", "centerpoint-lon"=>22.8333302, "name"=>[{"content"=>"ALASTARO", "lang"=>"FI"}, {"content"=>"ALASTARO", "lang"=>"SV"}], "province"=>{"name"=>""}, "radius"=>20, "merikotka-suuralue"=>"R"},
             {"id"=>"ALATOR", "ely-centre"=>{"content"=>13, "name"=>"Lapin ELY"}, "centerpoint-lat"=>66, "old-county"=>{"content"=>12, "name"=>"LAPPI, FINLAND"}, "joined-to"=>"", "centerpoint-lon"=>24.3333302, "name"=>[{"content"=>"ALATORNIO", "lang"=>"FI"}, {"content"=>"NEDERTORNEÅ", "lang"=>"SV"}], "province"=>{"name"=>""}, "radius"=>40, "merikotka-suuralue"=>"P"},
             {"id"=>"ALAVET", "ely-centre"=>{"content"=>10, "name"=>"Etelä-Pohjanmaan ELY"}, "centerpoint-lat"=>63.7000008, "old-county"=>{"content"=>9, "name"=>"VAASA, FINLAND"}, "joined-to"=>"", "centerpoint-lon"=>23.4166698, "name"=>[{"content"=>"ALAVETELI", "lang"=>"FI"}, {"content"=>"NEDERVETIL", "lang"=>"SV"}], "province"=>{"name"=>""}, "radius"=>20, "merikotka-suuralue"=>"N"},
             {"id"=>"ALAVIE", "ely-centre"=>{"content"=>11, "name"=>"Pohjois-Pohjanmaan ELY"}, "centerpoint-lat"=>64.1666565, "old-county"=>{"content"=>11, "name"=>"OULU, FINLAND"}, "joined-to"=>"ALAVIE", "centerpoint-lon"=>24.3333302, "name"=>[{"content"=>"ALAVIESKA", "lang"=>"FI"}, {"content"=>"ALAVIESKA", "lang"=>"SV"}], "province"=>{"content"=>17, "name"=>"Pohjois-Pohjanmaa"}, "radius"=>20, "merikotka-suuralue"=>"N"},
             {"id"=>"ALAVUS", "ely-centre"=>{"content"=>10, "name"=>"Etelä-Pohjanmaan ELY"}, "centerpoint-lat"=>62.5833333, "old-county"=>{"content"=>9, "name"=>"VAASA, FINLAND"}, "joined-to"=>"ALAVUS", "centerpoint-lon"=>23.6, "name"=>[{"content"=>"ALAVUS", "lang"=>"FI"}, {"content"=>"ALAVO", "lang"=>"SV"}], "province"=>{"content"=>14, "name"=>"Etelä-Pohjanmaa"}, "radius"=>32, "merikotka-suuralue"=>"N"},
             {"id"=>"ALUEVE", "ely-centre"=>{"name"=>""}, "centerpoint-lat"=>61.5, "old-county"=>{"content"=>13, "name"=>"SUOMI FINLAND"}, "joined-to"=>"", "centerpoint-lon"=>24.5, "name"=>[{"content"=>"ALUEVESI", "lang"=>"FI"}, {"content"=>"ALUEVESI", "lang"=>"SV"}], "province"=>{"name"=>""}, "radius"=>500, "merikotka-suuralue"=>""},
             {"id"=>"ANGELN", "ely-centre"=>{"content"=>2, "name"=>"Varsinais-Suomen ELY"}, "centerpoint-lat"=>60.2999992, "old-county"=>{"content"=>2, "name"=>"TURKU - PORI, FINLAND"}, "joined-to"=>"", "centerpoint-lon"=>22.9166698, "name"=>[{"content"=>"ANGELNIEMI", "lang"=>"FI"}, {"content"=>"ANGELNIEMI", "lang"=>"SV"}], "province"=>{"name"=>""}, "radius"=>20, "merikotka-suuralue"=>"R"},
             {"id"=>"ANJALA", "ely-centre"=>{"content"=>5, "name"=>"Kaakkois-Suomen ELY"}, "centerpoint-lat"=>60.75, "old-county"=>{"content"=>5, "name"=>"KYMI, FINLAND"}, "joined-to"=>"", "centerpoint-lon"=>26.75, "name"=>[{"content"=>"ANJALA", "lang"=>"FI"}, {"content"=>"ANJALA", "lang"=>"SV"}], "province"=>{"name"=>""}, "radius"=>20, "merikotka-suuralue"=>"T"},
             {"id"=>"AKOSKI", "ely-centre"=>{"content"=>5, "name"=>"Kaakkois-Suomen ELY"}, "centerpoint-lat"=>60.75, "old-county"=>{"content"=>5, "name"=>"KYMI, FINLAND"}, "joined-to"=>"", "centerpoint-lon"=>27.0833302, "name"=>[{"content"=>"ANJALANKOSKI", "lang"=>"FI"}, {"content"=>"ANJALANKOSKI", "lang"=>"SV"}], "province"=>{"name"=>""}, "radius"=>30, "merikotka-suuralue"=>"T"},
             {"id"=>"ANTTOL", "ely-centre"=>{"content"=>6, "name"=>"Etelä-Savon ELY"}, "centerpoint-lat"=>61.5833282, "old-county"=>{"content"=>6, "name"=>"MIKKELI, FINLAND"}, "joined-to"=>"", "centerpoint-lon"=>27.75, "name"=>[{"content"=>"ANTTOLA", "lang"=>"FI"}, {"content"=>"ANTTOLA", "lang"=>"SV"}], "province"=>{"name"=>""}, "radius"=>20, "merikotka-suuralue"=>"T"},
             {"id"=>"ARTJÄR", "ely-centre"=>{"content"=>3, "name"=>"Hämeen ELY"}, "centerpoint-lat"=>60.75, "old-county"=>{"content"=>1, "name"=>"UUSIMAA, FINLAND"}, "joined-to"=>"ORIMAT", "centerpoint-lon"=>26.0833302, "name"=>[{"content"=>"ARTJÄRVI", "lang"=>"FI"}, {"content"=>"ARTSJÖ", "lang"=>"SV"}], "province"=>{"name"=>""}, "radius"=>20, "merikotka-suuralue"=>"N"},
             {"id"=>"ASIKKA", "ely-centre"=>{"content"=>3, "name"=>"Hämeen ELY"}, "centerpoint-lat"=>61.216671, "old-county"=>{"content"=>4, "name"=>"HÄME, FINLAND"}, "joined-to"=>"ASIKKA", "centerpoint-lon"=>25.5833302, "name"=>[{"content"=>"ASIKKALA", "lang"=>"FI"}, {"content"=>"ASIKKALA", "lang"=>"SV"}], "province"=>{"content"=>7, "name"=>"Päijät-Häme"}, "radius"=>25, "merikotka-suuralue"=>"N"},
             {"id"=>"HELSIN", "ely-centre"=>{"content"=>3, "name"=>"Hurrdurr ELY"}, "centerpoint-lat"=>61.216671, "old-county"=>{"content"=>4, "name"=>"UUSIMAA, FINLAND"}, "joined-to"=>"", "centerpoint-lon"=>25.5833302, "name"=>[{"content"=>"HELSINKI", "lang"=>"FI"}, {"content"=>"HELSINGFORS", "lang"=>"SV"}], "province"=>{"content"=>7, "name"=>"Päijät-Häme"}, "radius"=>25, "merikotka-suuralue"=>"N"}]
  end

  def self.GetSpecies
    return {"species"=>[
        {"id"=>"HIPCALR", "name"=>[{"content"=>"Aavikkokultarinta", "lang"=>"FI"}, {"lang"=>"SV"}, {"lang"=>"EN"}, {"content"=>"Hippolais caligata rama", "lang"=>"LA"}], "euring-code"=>12562, "protection-status"=>""},
        {"id"=>"OENDES", "name"=>[{"content"=>"Aavikkotasku", "lang"=>"FI"}, {"content"=>"Ökenstenskvätta", "lang"=>"SV"}, {"content"=>"Desert Wheatear", "lang"=>"EN"}, {"content"=>"Oenanthe deserti", "lang"=>"LA"}], "euring-code"=>11490, "protection-status"=>""},
        {"id"=>"CLAHYE", "name"=>[{"content"=>"Alli", "lang"=>"FI"}, {"content"=>"Alfågel", "lang"=>"SV"}, {"content"=>"Long-tailed Duck", "lang"=>"EN"}, {"content"=>"Clangula hyemalis", "lang"=>"LA"}], "euring-code"=>2120, "protection-status"=>""},
        {"id"=>"POLSTE", "name"=>[{"content"=>"Allihaahka", "lang"=>"FI"}, {"content"=>"Alförrädare", "lang"=>"SV"}, {"content"=>"Steller's Eider", "lang"=>"EN"}, {"content"=>"Polysticta stelleri", "lang"=>"LA"}], "euring-code"=>2090, "protection-status"=>""},
        {"id"=>"PRUCOL", "name"=>[{"content"=>"Alppirautiainen", "lang"=>"FI"}, {"content"=>"Alpjärnsparv", "lang"=>"SV"}, {"content"=>"Alpine Accentor", "lang"=>"EN"}, {"content"=>"Prunella collaris", "lang"=>"LA"}], "euring-code"=>10940, "protection-status"=>""},
        {"id"=>"PHATRI", "name"=>[{"content"=>"Amerikan vesipääsky", "lang"=>"FI"}, {"lang"=>"SV"}, {"lang"=>"EN"}, {"content"=>"Phalaropus tricolor", "lang"=>"LA"}], "euring-code"=>5630, "protection-status"=>""},
        {"id"=>"GAVIMM", "name"=>[{"content"=>"Amerikanjääkuikka", "lang"=>"FI"}, {"content"=>"Svartnäbbad islom", "lang"=>"SV"}, {"content"=>"Great Northern Diver", "lang"=>"EN"}, {"content"=>"Gavia immer", "lang"=>"LA"}], "euring-code"=>40, "protection-status"=>""},
        {"id"=>"CALLLA", "name"=>[{"content"=>"Amerikansirri", "lang"=>"FI"}, {"lang"=>"SV"}, {"lang"=>"EN"}, {"content"=>"Calidris minutilla", "lang"=>"LA"}], "euring-code"=>5040, "protection-status"=>""},
        {"id"=>"HALALB", "name"=>[{"content"=>"Merikotka", "lang"=>"FI"}, {"content"=>"Havsörn", "lang"=>"SV"}, {"content"=>"White-tailed Sea Eagle", "lang"=>"EN"}, {"content"=>"Haliaeetus albicilla", "lang"=>"LA"}], "euring-code"=>2430, "protection-status"=>2}
    ]}
  end

  # not very pretty, but its a mock class, so like, whatever
  def self.GetRingerById(ringer_id)

    if ringer_id.to_s == 2890.to_s
      return {"ringers"=>{"ringer"=>{"id"=>2890, "mobile-phone"=>"", "recovery-letter-method"=>"kihla", "yearofbirth"=>1983, "email"=>"aallonmatti@hotmail.com", "address"=>{"street"=>"KORPELANTIE 153", "postcode"=>42800, "city"=>"HAAPAMÄKI"}, "name"=>"MATTI AALTO (2890)", "permit"=>{"content"=>"R: Larfus, fl / Perinf", "codes"=>"HR", "year"=>2014}, "lastname"=>"AALTO", "permission"=>1, "firstname"=>"MATTI", "language"=>"fi"}}}
    end
    if ringer_id.to_s == 1010.to_s
      return {"ringers"=>{"ringer"=>{"id"=>1010, "mobile-phone"=>"", "recovery-letter-method"=>"paper", "yearofbirth"=>"", "email"=>"", "address"=>{"street"=>"", "postcode"=>"", "city"=>""}, "name"=>"MATTI AHO (1010)", "permit"=>{"codes"=>"", "year"=>""}, "lastname"=>"AHO", "permission"=>0, "firstname"=>"MATTI", "language"=>"fi"}}}
    end
    return {"ringers"=>""}
  end

  def self.GetGenders
    return {"code"=>[{"id"=>9, "desc"=>[{"content"=>"Naaras", "lang"=>"FI"}, {"content"=>"Hona", "lang"=>"SV"}, {"content"=>"Female", "lang"=>"EN"}], "code"=>"N", "metadata"=>1}, {"id"=>9, "desc"=>[{"content"=>"Koiras", "lang"=>"FI"}, {"content"=>"Hane", "lang"=>"SV"}, {"content"=>"Male", "lang"=>"EN"}], "code"=>"K", "metadata"=>2}, {"id"=>9, "desc"=>[{"content"=>"Otaksuttavasti naaras", "lang"=>"FI"}, {"content"=>"Antagligen hona", "lang"=>"SV"}, {"content"=>"Presumably female", "lang"=>"EN"}], "code"=>"O", "metadata"=>3}, {"id"=>9, "desc"=>[{"content"=>"Luultavasti koiras", "lang"=>"FI"}, {"content"=>"Antagligen hane", "lang"=>"SV"}, {"content"=>"Presumably male", "lang"=>"EN"}], "code"=>"L", "metadata"=>4}, {"id"=>9, "desc"=>[{"content"=>"Naaraspukuinen", "lang"=>"FI"}, {"content"=>"Honafärgad", "lang"=>"SV"}, {"content"=>"Female type plumage", "lang"=>"EN"}], "code"=>"P", "metadata"=>5}, {"id"=>9, "desc"=>[{"content"=>"Intersukupuolinen", "lang"=>"FI"}, {"content"=>"Intersex", "lang"=>"SV"}, {"content"=>"Intersex", "lang"=>"EN"}], "code"=>"I", "metadata"=>6}]}
  end
end